### Login to obtain JWT token
POST http://localhost:8000/api/accounts/login/
Content-Type: application/json

{
    "username": "<USERNAME>",
    "password": "<PASSWORD>"
}

### Use the obtained token to access the Chilexpress coverage endpoint
GET http://localhost:8000/api/logistics/chilexpress/cobertura/99/
Authorization: Bearer <ACCESS_TOKEN>

### Prueba de cobertura
GET http://testservices.wschilexpress.com/georeference/api/v1.0/regions


### Prueba cobertura calle
POST https://testservices.wschilexpress.com/georeference/api/v1.0/streets/search HTTP/1.1
Content-Type: application/json
Cache-Control: no-cache
Ocp-Apim-Subscription-Key: <CHILEXPRESS_API_KEY_COBERTURA>

{
    "countyName": "SANTIAGO CENTRO",
    "streetName": "DOCTOR ALLENDE PADIN",
    "pointsOfInterestEnabled": true,
    "streetNameEnabled": true,
    "roadType": 0
}

### Prueba cobertura comuna
GET https://testservices.wschilexpress.com/georeference/api/v1.0/coverage-areas?RegionCode=RM&type=0 HTTP/1.1
Cache-Control: no-cache
Ocp-Apim-Subscription-Key: <CHILEXPRESS_API_KEY_COBERTURA>


### Cotizar
POST http://localhost:8000/api/logistics/chilexpress/cotizar/
Content-Type: application/json
Authorization: Bearer <ACCESS_TOKEN>

{
    "origen": "PROV",
    "destino": "LASCD",
    "peso": 2.5,
    "alto": 20,
    "ancho": 15,
    "largo": 30
}
